### ISSUE TITLE
Add software firewall rules checks

### ISSUE THREAD

**Issue by StephenBrown2** [rackerlabs/configsnap#34]
Support to document firewall rules, if in use, would be good:
e.g.
iptables:
```
iptables --list-rules
```
ufw:
```
ufw status numbered
```
firewalld:
```
cp /etc/firewalld?
```

**Comment by piersc** [comment]
Sounds good, but could we just go with recording iptables --list-rules for all platforms, since ufw and firewalld rules will be shown with iptables anyway? It makes it a little harder (but not impossible) if you're using this for rollback, but would be adequate for comparison purposes and keep things nice and simple.

**Comment by StephenBrown2** [comment]
If all of them are just an interface to iptables, then yeah, that should work fine. I was thinking of rollback as well, but for comparison purposes I agree a single command is better than three.

**Comment by piersc** [comment]
Fixed in https://github.com/rackerlabs/configsnap/pull/36
